### ISSUE TITLE
Thumbs Regex broken on Windows, use JSON HTML Templating instead?

### ISSUE THREAD

**Issue by antonizoon** [bibanon/BASC-Archiver#12]
Apparently the thumbs regex doesn't work on the windows version.

So when you open the HTML file, it fails to link to the internal thumbnails. However, the Image link conversion seems to work

But I think the real solution is to procedurally generate a JSON HTML templater, so we don't ever have to scrape CSS or HTML again

http://beebole.com/pure/

http://twigkit.github.io/tempo/

The question is how to load a local JSON file, since usually it's not allowed. There are some hacks here:

http://stackoverflow.com/a/18637657

**Comment by DanielOaks** [comment]
Thumbnails are fixed, new release pushed out.

**Comment by antonizoon** [comment]
Here's an explanation of what changed:

Sometime in 2015, 4chan stopped using `t.4cdn.org` (or even more confusingly, `0.t.4cdn.org` as we had to parse from it's HTML) for thumbnail URLs in it's threads. Instead, it uses `i.4cdn.org`. 

The BASC-Archiver was modified to support this [in this commit.](https://github.com/bibanon/BASC-Archiver/commit/a3cb5bef70255680b67ccf8bafe7cb1f29170725)

---

However, the `t.4cdn.org` URL still works, for now, and `t.4cdn.org` is  still on the 4chan API README. This is why we have left the URL alone for now on BASC-py4chan. Hopefully, they keep it that way, as it doesn't take up very much resources, and changing it would break compatiblity with Fuuka.
