### ISSUE TITLE
Fails to removed Archived threads from list (as opposed to 404 threads)

### ISSUE THREAD

**Issue by antonizoon** [bibanon/BASC-Archiver#37]
https://github.com/bibanon/BASC-Archiver/blob/master/basc_archiver/sites/fourchan.py#L232

This bug causes archived threads to never be removed from the list.

This line should be something like `is.404 or is.archived`,

**Comment by DanielOaks** [comment]
Implemented by bf62ec33f2d753b1db3f28105151fc3c04ddad64
