### ISSUE TITLE
Convert all references from is.4chan.org & is2.4chan.org to i.4chan.org

### ISSUE THREAD

**Issue by nick-s-b** [bibanon/BASC-Archiver#41]
Hi devs,
These two servers are extremely slow yet when you change them to i.4chan.org, all images download fast again. So the solution is to change all references to is. & is2. to i. Many other 4chan scripts do this automatically now.
Thanks!

**Comment by antonizoon** [comment]
Man who knows what they are doing on the backend? I will make this change on BASC-py4chan for now, but contact us immediately if:

1. i.4chan.org is discontinued for whatever reason
2. The other 4chan scripts start using something else

**Comment by antonizoon** [comment]
Hey wait are you sure it is i.4chan.org? Not i.4cdn.org?

**Comment by antonizoon** [comment]
I checked 4chanX and they use i.4cdn.org. https://i.4cdn.org/qa/1486435366308.png

Originally, some change in the backend caused i.4cdn.org not to work. But i guess they left it active and it's been around for so long I'm going to just switch back to it.

Immediately contact us if i.4cdn.org stops working.

**Comment by antonizoon** [comment]
Use pip to upgrade BASC-py4chan to 0.6.3 to regain the i.4cdn.org URL.
