### ISSUE TITLE
Support 4chan's 4channel.org domain

### ISSUE THREAD

**Issue by jl3arner** [bibanon/BASC-Archiver#50]
Context [from Wikipedia](https://en.wikipedia.org/wiki/4chan#History):

> On November 17, 2018, it was announced that the site would be split into two, with the work-safe boards moved to a new domain, 4channel.org, while the NSFW boards would remain on the 4chan.org domain.

Error output:

    $ thread-archiver --version
    BASC-Archiver v0.9.8
    $ thread-archiver "https://boards.4channel.org/g/thread/51971506"
    Starting download
    We could not find a valid archiver for: https://boards.4channel.org/g/thread/51971506
    
    We could not find any of the supplied threads, exiting.

**Comment by antonizoon** [comment]
https://github.com/bibanon/BASC-Archiver/commit/988c6f703dfac0afba7bc767c1388a29b9c68be4

patched in v0.9.9, just changed the url regex and no other changes were needed.

**Comment by jl3arner** [comment]
Appreciate the fast turnaround. Thanks for maintaining this tool. 😄
