### ISSUE TITLE
Add Delay to Image Downloading, and Handle Connection Refused

### ISSUE THREAD

**Issue by antonizoon** [bibanon/BASC-Archiver#8]
After scaling up the 4chan archiver for heavy duty scraping, I think we should really add a delay setting to image/file downloading (not just thread inquiry). 4chan starts to give us Connection Refused errors.

Also we need to handle [the Connection Refused error](http://pastebin.com/shPcwB6u) in some safe manner.

**Comment by DanielOaks** [comment]
Hmm, something like waiting X ms between each image download, or are you thinking something different?

**Comment by antonizoon** [comment]
Yes, make a configurable delay specifically for file downloads. I think in the `download()` function.

**Comment by DanielOaks** [comment]
Sounds good, should be pretty simple

**Comment by antonizoon** [comment]
Alright, I added the option to delay image/thumbnail download.
